### ISSUE TITLE
Event Mapper issue 

### ISSUE THREAD

**Issue by PabloTab** [odpi/egeria-connector-apache-atlas#104]
While trying to set up the connector Provider given in the Postman collection, an error was found:

POST:
{{baseURL}}/open-metadata/admin-services/users/{{user}}/servers/{{server}}/local-repository/event-mapper-details?connectorProvider=org.odpi.egeria.connectors.apache.atlas.eventmapper.ApacheAtlasOMRSRepositoryEventMapperProvider&eventSource={{atlas_kafka}}

"**exceptionClassName**": "org.odpi.openmetadata.adminservices.ffdc.exception.OMAGConfigurationErrorException",
    "**exceptionErrorMessage**": _"OMAG-ADMIN-500-001 Method setLocalRepositoryEventMapper for OMAG server ATLAS-B4All_MDS returned an unexpected exception of java.lang.ClassNotFoundException with message org.odpi.egeria.connectors.apache.atlas.eventmapper.ApacheAtlasOMRSRepositoryEventMapperProvider",_

**Comment by cmgrote** [comment]
Hi @PabloTab -- thanks for trying the connector.  This error typically indicates that the connector jar file cannot be found in the location given by the `LOADER_PATH` environment variable (or the `-Dloader.path=...` parameter sent to the JVM at OMAG server startup).

I've tried to clarify this further in the instructions, in particular adding a "quick-start" section of sorts here: https://github.com/odpi/egeria-connector-apache-atlas#tldr

I've also just re-tested and confirmed that the Postman samples provided in this repository do work, so long as the OMAG platform has been started with the connector in its `loader.path` (per the instructions).

If you are still facing the problem after following the updated instructions, can you please clarify:

- What operating system (and version) you're attempting to run on
- What version of the connector you're using (eg. the jar file name)
- What version of the OMAG platform you're using (eg. the jar file name)
- Your environment variables (`env`)
- What version of the JVM you're using (`java -version`)
- The command you're using to start the OMAG platform (`java ...`)

**Comment by PabloTab** [comment]
Hi Christopher,

Thank you very much for your reply and very clear explanation.
This has solved my issue!
