### ISSUE TITLE
Add to SonarCloud

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria-connector-apache-atlas#39]
Can we setup a project for this repo under the ODPi org in Sonarcloud, to get quality checks against this repo?  (Let me know if we should assign to someone else -- but I don't have admin privileges to do it myself 🙂)

**Comment by planetf1** [comment]
Will let @bramwelt answer though I think the process is to open an issue at https://jira.linuxfoundation.org/servicedesk/customer/portal/2 ?

**Comment by planetf1** [comment]
Note also that if you want to run findsecbugs/spotbugs, follow the pattern in the egeria pom to use spot bugs (and also pmd) and then ensure the sonar upload adds these in

**Comment by cmgrote** [comment]
Sorry, I'm obviously clueless on the correct procedures -- have raised a ticket there instead, closing these...  Thanks for the pointer!

**Comment by planetf1** [comment]
For clarification, the pmr and findbugs scan pick up some additional issues beyond that which sonar had been picking up. Both are well respected in the sonar community (using findsecbugs). Sonar has support for both as external scanners, so we provide this option in the build to either run manually, or to run as part of the sonar build task on azure pipelines.
